server:
  port: 9091
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shanghaimuseum?serverTimezone=GMT%2b8
    #????????
    username: root
    password: Wh211310306_
    #创建连接信息

    http.cors.enabled: true
    http.cors.allow-origin: "*"
mybatis:
  mapper-locations: classpath:mapper/*.xml  #扫描所有mybatis文件#
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

